services:
  - type: web
    name: code-review-app
    env: static
    buildCommand: npm install && npm run build
    publishDirectory: ./build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_GEMINI_API_KEY
        sync: false
    repo:
      provider: github
      branch: main
    autoDeploy: true
    healthCheckPath: /
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - yarn.lock
    routes:
      - type: rewrite
        source: /*
        destination: /index.html